from astra.tools.bitmask import BitMask


class StarBitMask(BitMask):
    """
    BitMask class for APOGEE star bitmask (APOGEE_STARFLAG)
    """

    name = [
        "BAD_PIXELS",
        "COMMISSIONING",
        "BRIGHT_NEIGHBOR",
        "VERY_BRIGHT_NEIGHBOR",
        "LOW_SNR",
        "",
        "",
        "",
        "",
        "PERSIST_HIGH",
        "PERSIST_MED",
        "PERSIST_LOW",
        "PERSIST_JUMP_POS",
        "PERSIST_JUMP_NEG",
        "",
        "",
        "SUSPECT_RV_COMBINATION",
        "SUSPECT_BROAD_LINES",
        "BAD_RV_COMBINATION",
        "RV_REJECT",
        "RV_SUSPECT",
        "MULTIPLE_SUSPECT",
        "RV_FAIL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ]
    level = [
        1,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ]

    descrip = [
        "Spectrum has many bad pixels (>20%):  BAD",
        "Commissioning data (MJD<55761), non-standard configuration, poor LSF: WARN",
        "Star has neighbor more than 10 times brighter: WARN",
        "Star has neighbor more than 100 times brighter: BAD",
        "Spectrum has low S/N (S/N<5)",
        "",
        "",
        "",
        "",
        "Spectrum has significant number (>20%) of pixels in high persistence region: WARN",
        "Spectrum has significant number (>20%) of pixels in medium persistence region: WARN",
        "Spectrum has significant number (>20%) of pixels in low persistence region: WARN",
        "Spectrum show obvious positive jump in blue chip: WARN",
        "Spectrum show obvious negative jump in blue chip: WARN",
        "",
        "",
        "RVs from synthetic template differ significantly (~2 km/s) from those from combined template: WARN",
        "Cross-correlation peak with template significantly broader than autocorrelation of template: WARN",
        "RVs from synthetic template differ very significatly (~10 km/s) from those from combined template: BAD",
        "Rejected visit because cross-correlation RV differs significantly from least squares RV",
        "Suspect visit (but used!) because cross-correlation RV differs slightly from least squares RV",
        "Suspect multiple components from Gaussian decomposition of cross-correlation",
        "RV failure",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ]

    def persist(self):
        """
        Returns bitwise OR of all persistence bits
        """
        return self.getval(
            [
                "PERSIST_HIGH",
                "PERSIST_MED",
                "PERSIST_LOW",
                "PERSIST_JUMP_POS",
                "PERSIST_JUMP_NEG",
            ]
        )


class PixelBitMask(BitMask):
    """
    BitMask class for APOGEE pixel bitmask (APOGEE_PIXMASK)
    """

    name = [
        "BADPIX",
        "CRPIX",
        "SATPIX",
        "UNFIXABLE",
        "BADDARK",
        "BADFLAT",
        "BADERR",
        "NOSKY",
        "LITTROW_GHOST",
        "PERSIST_HIGH",
        "PERSIST_MED",
        "PERSIST_LOW",
        "SIG_SKYLINE",
        "SIG_TELLURIC",
        "NOT_ENOUGH_PSF",
        "",
        "FERRE_MASK",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ]

    level = [
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
    ]

    maskcontrib = [
        0.1,
        0.1,
        0.1,
        0.1,
        0.1,
        0.1,
        0.1,
        0.1,
        0.1,
        0.1,
        0.1,
        0.1,
        0.1,
        0.1,
        0.1,
        0.0,
        0.1,
        0.1,
        0.1,
        0.1,
        0.1,
        0.1,
        0.1,
        0.0,
        0.1,
        0.1,
        0.1,
        0.1,
        0.1,
        0.1,
        0.1,
        0.0,
    ]

    descrip = [
        "Pixel marked as BAD in bad pixel mask or from strong persistence jump",
        "Pixel marked as cosmic ray in ap3d",
        "Pixel marked as saturated in ap3d",
        "Pixel marked as unfixable in ap3d",
        "Pixel marked as bad as determined from dark frame",
        "Pixel marked as bad as determined from flat frame",
        "Pixel set to have very high error (not used)",
        "No sky available for this pixel from sky fibers",
        "Pixel falls in Littrow ghost, may be affected",
        "Pixel falls in high persistence region, may be affected",
        "Pixel falls in medium persistence region, may be affected",
        "Pixel falls in low persistence region, may be affected",
        "Pixel falls near sky line that has significant flux compared with object",
        "Pixel falls near telluric line that has significant absorption",
        "Less than 50 percent PSF in good pixels",
        "",
        "Pixel masked by FERRE mask < 0.001",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ]
